backend:
    pattern:  /admin/
    defaults: { _controller: BackendBundle:Default:index}

_backend:
    pattern: /admin
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: backend}
