TipoPublicacion:
    pattern:  /admin/tipopublicacion
    defaults: { _controller: PublicacionesBundle:TipoPublicacion:index }
    
_TipoPublicacion:
    pattern: /admin/tipopublicacion/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: tipopublicacion}

TipoPublicacion_new:
    pattern:  /admin/tipopublicacion/new
    defaults: { _controller: PublicacionesBundle:TipoPublicacion:new }

TipoPublicacion_edit:
    pattern:  /admin/tipopublicacion/edit/{id}
    defaults: { _controller: PublicacionesBundle:TipoPublicacion:edit }

TipoPublicacion_show:
    pattern:  /admin/tipopublicacion/show/{id}
    defaults: { _controller: PublicacionesBundle:TipoPublicacion:show }

TipoPublicacion_create:
    pattern:  /admin/tipopublicacion/create
    defaults: { _controller: PublicacionesBundle:TipoPublicacion:create }

TipoPublicacion_update:
    pattern:  /admin/tipopublicacion/update/{id}
    defaults: { _controller: PublicacionesBundle:TipoPublicacion:update }

TipoPublicacion_delete:
    pattern:  /admin/tipopublicacion/delete/{id}
    defaults: { _controller: PublicacionesBundle:TipoPublicacion:delete}

Publicacion:
    pattern:  /{_locale}/publicaciones
    defaults: { _controller: PublicacionesBundle:Publicacion:index }

_Publicacion:
    pattern: /{_locale}/publicaciones/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: Publicacion}


Publicacion_new:
    pattern:  /admin/publicaciones/new/{tipo}
    defaults: { _controller: PublicacionesBundle:Publicacion:newLibro}

Publicacion_edit:
    pattern:  /admin/publicaciones/edit/{id}
    defaults: { _controller: PublicacionesBundle:Publicacion:edit }

Publicacion_backend:
    pattern:  /admin/publicaciones
    defaults: { _controller: PublicacionesBundle:Publicacion:indexBackend }

Publicacion_show:
    pattern:  /admin/publicaciones/show/{id}
    defaults: { _controller: PublicacionesBundle:Publicacion:show }

Publicacion_create:
    pattern:  /admin/publicaciones/create
    defaults: { _controller: PublicacionesBundle:Publicacion:create }

Publicacion_update:
    pattern:  /admin/publicaciones/update/{id}
    defaults: { _controller: PublicacionesBundle:Publicacion:update }

Publicacion_delete:
    pattern:  /admin/publicaciones/delete/{id}
    defaults: { _controller: PublicacionesBundle:Publicacion:delete}

Publicacion_print:
    pattern:  /admin/publicaciones/print
    defaults: { _controller: MiembroBundle:Miembro:print }

Publicacion_miembro_new:
    pattern:  /admin/publicaciones/{id}/miembros/new
    defaults: { _controller: MiembroBundle:MiembroPublicacion:new }

Publicacion_miembro_delete:
    pattern:  /admin/publicaciones/{idp}/miembros/{idm}/delete
    defaults: { _controller: MiembroBundle:MiembroPublicacion:delete }

Publicacion_miembros:
    pattern:  /admin/publicaciones/miembros/{id}
    defaults: { _controller: PublicacionesBundle:Publicacion:publicacionMiembros }
