entidad_financiera:
    resource: "@EntidadFinancieraBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es

portada:
    resource: "@PortadaBundle/Resources/config/routing.yml"
    requirements:
        _locale: en|es

publicaciones:
    resource: "@PublicacionesBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es

proyecto:
    resource: "@ProyectoBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es

miembro:
    resource: "@MiembroBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

