proyecto:
    pattern:  /{_locale}/proyectos
    defaults: { _controller: ProyectoBundle:Proyecto:index }

Proyecto:
    pattern:  /{_locale}/proyectos
    defaults: { _controller: ProyectoBundle:Proyecto:index }

_proyecto:
    pattern: /{_locale}/proyectos/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: Proyecto}

proyecto_backend:
    pattern:  /admin/proyectos
    defaults: { _controller: ProyectoBundle:Proyecto:indexBackend}

proyecto_new:
    pattern:  /admin/proyectos/new
    defaults: { _controller: ProyectoBundle:Proyecto:new }

proyecto_edit:
    pattern:  /admin/proyectos/edit/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:edit }


proyecto_miembros:
    pattern:  /admin/proyectos/miembros/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:proyectoMiembros }

proyecto_show:
    pattern:  /admin/proyectos/show/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:show }

proyecto_create:
    pattern:  /admin/proyectos/create
    defaults: { _controller: ProyectoBundle:Proyecto:create }

proyecto_update:
    pattern:  /admin/proyectos/update/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:update }

proyecto_delete:
    pattern:  /admin/proyectos/delete/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:delete}

proyecto_print:
    pattern:  /admin/proyectos/print
    defaults: { _controller: ProyectoBundle:Proyecto:print }