proyecto:
    pattern:  /{_locale}/Proyecto
    defaults: { _controller: ProyectoBundle:Proyecto:index }

Proyecto:
    pattern:  /{_locale}/Proyecto
    defaults: { _controller: ProyectoBundle:Proyecto:index }

_proyecto:
    pattern: /{_locale}/Proyecto/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: Proyecto}

proyecto_backend:
    pattern:  /backend/Proyecto
    defaults: { _controller: ProyectoBundle:Proyecto:indexBackend}

proyecto_new:
    pattern:  /backend/Proyecto/new
    defaults: { _controller: ProyectoBundle:Proyecto:new }

proyecto_edit:
    pattern:  /backend/Proyecto/edit/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:edit }


proyecto_miembros:
    pattern:  /backend/Proyecto/miembros/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:proyectoMiembros }

proyecto_show:
    pattern:  /backend/Proyecto/show/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:show }

proyecto_create:
    pattern:  /backend/Proyecto/create
    defaults: { _controller: ProyectoBundle:Proyecto:create }

proyecto_update:
    pattern:  /backend/Proyecto/update/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:update }

proyecto_delete:
    pattern:  /backend/Proyecto/delete/{id}
    defaults: { _controller: ProyectoBundle:Proyecto:delete}