miembro:
    pattern:  /{_locale}/miembro
    defaults: { _controller: MiembroBundle:Miembro:index }

_miembro:
    pattern: /{_locale}/miembros/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: miembro}

miembro_new:
    pattern:  /admin/miembros/new
    defaults: { _controller: MiembroBundle:Miembro:new }

miembro_edit:
    pattern:  /admin/miembros/edit/{id}
    defaults: { _controller: MiembroBundle:Miembro:edit }

miembro_show:
    pattern:  /admin/miembros/show/{id}
    defaults: { _controller: MiembroBundle:Miembro:show }

miembro_create:
    pattern:  /admin/miembros/create
    defaults: { _controller: MiembroBundle:Miembro:create }

miembro_update:
    pattern:  /admin/miembros/update/{id}
    defaults: { _controller: MiembroBundle:Miembro:update }

miembro_delete:
    pattern:  /admin/miembros/delete/{id}
    defaults: { _controller: MiembroBundle:Miembro:delete}

miembro_backend:
    pattern:  /admin/miembros
    defaults: { _controller: MiembroBundle:Miembro:indexBackend }

miembro_print:
    pattern:  /admin/miembros/print
    defaults: { _controller: MiembroBundle:Miembro:print }

proyecto_miembro_new:
    pattern:  /admin/proyectos/{id}/miembros/new
    defaults: { _controller: MiembroBundle:MiembroProyecto:new }

